set(_CATKIN_CURRENT_PACKAGE "stewart_platform")
set(stewart_platform_VERSION "0.0.0")
set(stewart_platform_MAINTAINER "Hadi Yada <yadavari@itu.edu.tr>")
set(stewart_platform_PACKAGE_FORMAT "2")
set(stewart_platform_BUILD_DEPENDS "openai_ros" "roscpp" "rospy" "std_msgs")
set(stewart_platform_BUILD_EXPORT_DEPENDS "openai_ros" "roscpp" "rospy" "std_msgs")
set(stewart_platform_BUILDTOOL_DEPENDS "catkin")
set(stewart_platform_BUILDTOOL_EXPORT_DEPENDS )
set(stewart_platform_EXEC_DEPENDS "openai_ros" "roscpp" "rospy" "std_msgs")
set(stewart_platform_RUN_DEPENDS "openai_ros" "roscpp" "rospy" "std_msgs")
set(stewart_platform_TEST_DEPENDS )
set(stewart_platform_DOC_DEPENDS )
set(stewart_platform_URL_WEBSITE "")
set(stewart_platform_URL_BUGTRACKER "")
set(stewart_platform_URL_REPOSITORY "")
set(stewart_platform_DEPRECATED "")